spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: test
    password: test
    url: jdbc:oracle:thin:@//42.192.169.11:1521/orclpdb1
  redis:
    host: 8.133.185.160
    port: 6379


mybatis:
  type-aliases-package: com.tongji.express.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: com.tongji.express.mapper


# 拦截器相关的配置
interceptors:
  # 不需要进行鉴权的接口地址，用逗号隔开
  auth-ignore-uris: /account/register,/account/enroll,/worker/registry,/worker/login


mybatis-plus:
  type-aliases-package: com.tongji.express.entity
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com.tongji.express.mapper: DEBUG
