spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: test
    password: test
    url: jdbc:oracle:thin:@//42.192.169.11:1521/orclpdb1
    hikari:
      max-lifetime: 600000
  redis:
    host: 139.224.49.108
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 10
        min-idle: 0


mybatis:
  type-aliases-package: com.tongji.express.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: com.tongji.express.mapper

server:
  port: 9999
  ssl:
    key-store: classpath:4911900_www.csystd.cn.pfx
    key-store-password: 5doDH01I
    key-store-type: PKCS12
    enabled: true



# 拦截器相关的配置
interceptors:
  # 不需要进行鉴权的接口地址，用逗号隔开
  auth-ignore-uris: /account/register,/account/enroll,/worker/registry,/worker/login





mybatis-plus:
  type-aliases-package: com.tongji.express.entity
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com.tongji.express.mapper: DEBUG
